import React from "react";
import Head from "next/head";
import Header from "../common/Header/Header";
import { Container } from "@chakra-ui/react";

function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      {/* <Container maxW="container.lg"  color="#262626"> */}
        {/* <main>{children}</main> */}
      {/* </Container> */}
    </>
  );
}

export default Layout;
